name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }} example

    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda install pylint wxpython pillow pytest-shutil numpy
      - name: Analysing the code with pylint
        run: |
          pylint `ls -L|grep .py$|xargs`
